### ISSUE TITLE
Sort out standard for suspend/startup etc packages

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#147]
We should sort out how packages that add suspend/startup/shutdown images should be handled. Likely we'll need to implement an application that allows you to enable a specific screen from the installed packages.

**Comment by LinusCDE** [comment]
Good idea.

Would be cool if packages could choose to use a sleep screen provided by the current launcher from the draft file like:
```
name=...
description=...
...
sleepImgFile=... # (maybe searched in /opt/etc/draft/sleep_images)
disableSleepScreen=false # Optional for apps that already have a sleep screen and want it be used instead of a global one
```

Though maybe I misunderstood it. I know that you have a (sub?)package to handle the sleep screen in oxide. I don't know of other packages, yet.

I think the problem is similar to how to handle which launcher to use. Probably just installing one package at a time would be helpful. Though I see the problem for a launcher having to know which to use. Maybe we would need a similar system to the draft files where sleep screen providing apps can register themselves and a launcher can select one. Having a symlink or textfile for the selection would probably be best to ensure every launcher uses the same settings and the user can choose one from the cli as well.

Pseudo-Example:
```
$ ls /opt/etc/sleepprovider.d/
oxide_sleepscreen.conf
some_other_sleep_screen.conf
$ cat  /opt/etc/sleepprovider.d/oxide_sleepscreen.conf
name=Oxide Sleepscreen # Display name for selection in launchers
execute=/opt/bin/oxide --sleep-screen
$ cat /opt/etc/sleepprovider.conf
selected=oxide_sleepscreen.conf
```

This is just how I could imagine it working. You'll probably have a better idea of how this could work properly. Adding a custom app that can manage this selection would also make this approach more launcher-independant as they wouldn't need to add a own selection for it. Launchers then would probably only implement that they check what file is selected and run the sleep screen on suspend and not care about how a user can change it.

**Comment by Eeems** [comment]
I'm not really a fan of `/opt/etc/draft/sleep_images`. That said having the package format support the sleep images does seem like a great option. Having the sleep provider of some sort that provides an interface for managing which ones you have enabled on device would be ideal. Perhaps we have a base command line tool, and a reference UI implementation and allow others to create their own interface for managing it. That way there could be an oxide specific application that makes use of the oxide features, but users who choose not to use oxide still have a UI option.

So perhaps we store the images ("themes" if you will) in `/opt/lib` somewhere. and have the tool that handles installing based on the `/opt/etc` config into `/usr/lib/remarkable`

**Comment by LinusCDE** [comment]
That sounds great. Would be cool to know from people, who want to implement them, what features would be needed/wished. I basicially got inspired by the way we do draft files (which probably comes from the way, DEs do .desktop files).

**Comment by Eeems** [comment]
Perhaps you could post on reddit asking for what people want? That or we implement something initially and post that asking for feedback?

**Comment by LinusCDE** [comment]
Done: https://www.reddit.com/r/RemarkableTablet/comments/kk7xum/

Any suggestion of a change I should make to the post. Could probably be more polished / on point.
