### ISSUE TITLE
Installation problem: Toltec-bootstrap is not in the stable branch

### ISSUE THREAD

**Issue by jonahweissman** [matteodelabre/toltec#174]
I tried to install toltec with the bootstrap script, but the script failed when it tried to run `opkg install toltec-bootstrap`. From what I can tell, `toltec-bootstrap` is not available on the stable branch, only on testing. I was able to work around this issue by installing with
```
$ toltec_branch=testing bash bootstrap
```
And then changing the line
```
src/gz toltec https://toltec-dev.org/testing
```
in `/opt/etc/opkg.conf` to
```
src/gz toltec https://toltec-dev.org/stable
```
But it would probably be easier for new users if they didn't have to do this.

I'm assuming that `toltec-bootstrap` is not on the stable branch so that it doesn't appear in the package list that users read. Is there a better way to do this?

**Comment by LinusCDE** [comment]
Boostrap forcing the default use of stable and then having these problems should be addressed indeed. We should treat any toltec repo url in `opkg.conf` as the choice of the user no matter what `toltec_branch` is selected (or just if the env isn't specified).

Those things are definitely things we need to iron out before the official [Community Rollout](https://github.com/toltec-dev/toltec/milestone/1).

Any ideas @Eeems ?

@matteodelabre We should probably make the stable branch the default one. That would make versioning the readme also easiyer since it would reflect the state of it's own branch. Even if this might induce a bit more trouble for devs creating their first PR, basing and merging their changes into stable if not careful.

**Comment by Eeems** [comment]
toltec-bootstrap was just merged in to testing the other day and will be in stable as part of the next stable merge window.

We should make sure that the readme points people at the stable version of the script instead of the testing one. That was an oversight of the PR to merge it in.

I do agree though that we should make stable the default branch, although I'm not sure if GitHub likes to play nice with opening PRs by default etc.

**Comment by LinusCDE** [comment]
> I do agree though that we should make stable the default branch, although I'm not sure if GitHub likes to play nice with opening PRs by default etc.

Good point. Also not sure on that one. Switching to stable would probably cause a lot of wrong PRs even from ourselves. :grin:

**Comment by Eeems** [comment]
We could easily add a script to tell us to switch the branch.

**Comment by matteodelabre** [comment]
There is a longstanding request for GitHub to make the default PR branch and the default view branch two separate settings (https://github.com/isaacs/github/issues/1401). Setting the default branch to `testing` makes things easier for devs. Setting it to `stable` makes things easier for users. The second makes more sense for several reasons:

1. We can’t expect all users to know that there are separate `stable` and `testing` branches.
2. The README defaults to the `testing` branch while the bootstrap script defaults to the `stable` branch, which is inconsistent.
3. There will probably be more general users than devs on this project, so we should favor their experience.

Therefore, if everyone agrees, I’ll switch the default branch to `stable`.

**Comment by Eeems** [comment]
We will probably need to add a PR check to make sure we don't accidentally merge into stable for non-merge window PRs.

**Comment by matteodelabre** [comment]
Will be fixed in the next merge window (this week-end). Thanks for reporting @jonahweissman!
