### ISSUE TITLE
clean up utils section

### ISSUE THREAD

**Issue by raisjn** [matteodelabre/toltec#203]
the util and utils section are the largest sections and have some apps that can be re-sectioned. some ideas for sections:

* streaming
* runtimes (or libraries?)
* terminals
* input

**Comment by Eeems** [comment]
What's the current breakdown of packages we can put in those sections already?

**Comment by raisjn** [comment]
runtime: 

* aspnet-runtime, aspnet-targeting-pack, dotnet-host, dotnet-profile, dotnet-runtime, dotnet-sdk, dotnet-targeting-pack, netstandard-targeting-pack

terminals (or terminal software):

* micro
* fingerterm

streaming:

* vnsee
* restream

input:

* rmservewacominput
* evtest

i think splitting the dotnet stuff out is the biggest bang for buck

**Comment by Eeems** [comment]
So micro is a text editor for the terminal. I'm not convinced that `terminals` is a good name for the section if micro is in it.

As for `runtime`, I do think that `libraries` is a better name, but due to our target userbase, they might confuse that with something to do with books. We'll have to workshop that name a bit more. It's a good section to break out though.

I do like the `streaming` section as well, but I'm not sure if that's the right name for it. Can't think of an alternative though.

I think `input` makes sense to leave in `utils`

**Comment by matteodelabre** [comment]
I think we should also take this opportunity to document all sections properly in <https://github.com/toltec-dev/toltec/blob/testing/docs/package.md#section>.

**Comment by matteodelabre** [comment]
What about an `admin` category for system management tools? ([Like Debian.](https://packages.debian.org/stable/admin/)) Could include `nao` and `erode`, for example.

**Comment by matteodelabre** [comment]
> As for `runtime`, I do think that `libraries` is a better name, but due to our target userbase, they might confuse that with something to do with books. We'll have to workshop that name a bit more. It's a good section to break out though.

We could also make a `devel` section for packages which only support other apps. So, all .NET/ASP-related packages, plus for example `simple` & `appmarkable`.

> I do like the `streaming` section as well, but I'm not sure if that's the right name for it. Can't think of an alternative though.

Maybe `screensharing`?

**Comment by LinusCDE** [comment]
Should we also recategorize the util (singular) section? Seeing that makes it silly that we have both util and utils and remove every single package from the utils section but keep util untouched.

**Comment by raisjn** [comment]
if others are up for it, let's add 3 new sections: devel, admin, screensharing and we'll add more over time
