### ISSUE TITLE
[rm2fb] re-consider way of specifying LD_PRELOAD for launchers

### ISSUE THREAD

**Issue by raisjn** [matteodelabre/toltec#337]
compiling binaries for usage in toltec testing channel requires using patchelf on them. 

this is a strange situation since rM1 does not require rm2fb or necessarily have it installed, so a binary that has been patchelf'd is incompatible with rM1 that does not have toltec installed with rm2fb. i think this means that i need to supply people with two sets of binaries and compilation instructions: one for toltec enabled rM1/rM2 and one for rM1 without toltec

**Comment by raisjn** [comment]
actually, never mind me

**Comment by danshick** [comment]
I'm confused. If a package is in Toltec, it has a build recipe designed to produce binaries that are distributed as part of Toltec. If you build an app with a Makefile or similar build infrastructure directly from it's repo, it likely wont produce patchelf'd binaries. The patchelf'ing only happens for Toltec in a Toltec package recipe.

**Comment by raisjn** [comment]
previously: all launchers had LD_PRELOAD enabled for them through a systemd override. any app launched through launcher will have rm2fb placed onto it, regardless if app comes from toltec or not. 

now: launcher is patchelf and there is no global LD_PRELOAD. if the launcher wants to launch an app, it needs to setup LD_PRELOAD for that app or know that is has been patchelfed. 

now: if i want to give someone a binary, the binary needs to be patchelf (if running on rM2) or it needs to **not** be patchelf (if running on non-toltec rM1). it is ok to give patchelf binary to rM1 with toltec and non-patchelf binary to rM2 without toltec. 

as an example: remux either needs to be compiled with patchelf or not. if someone want to use my repo to compile remux and use it with toltec, they will need to use the patchelf version. if they have an rM1 and no toltec, they will need to use the non-patchelf. which do i choose by default? either way, some percentage of people will be confused when they didn't need to be

**Comment by danshick** [comment]
Please take everything below with a grain of salt. Maybe I'm still wrong in my understanding of your concern.

I think you should distribute a non-patchelf version of your launcher from your repo and let patchelf happen only in Toltec. 

I think it is reasonable to expect that folks who aren't using Toltec will:

A.) Have an rM1 and not need a preload or rm2fb and will not want any patchelf or preload of any kind.

-or-

B.) Have an rM2 and have installed rm2fb manually and understand the need for both it and the shim/preload. Instructions for that (including the global systemd override setup) should be kept with rm2fb in its repo with manual install instructions.

Users who are using Toltec will have a package built automatically for their device that includes exactly what is needed for launchers and apps to work without tweaking.

The only case where there is an issue AFAICS is a user who has Toltec on an rM2, used it to install remux (which is therefore patchelf'd) and wants to use that launcher to launch a non-Toltec compiled and installed app.

What should really happen is non-Toltec apps shouldn't land in the same directory as Toltec apps and if you want to help out this user base, consider where the app is installed when deciding how to launch it. Because this isn't a sure thing, maybe you could ask `opkg` to elicit all of the files it has installed and LD_PRELOAD anything not belonging to one of its packages that originates from `toltec`. Arch has a `pacman -Ql` feature that could achieve this and I bet `opkg` does too.

We are already using `/opt` which is kind of unfortunate because ideally `/opt/bin` is where manually installed packages should go and package managers should target `/usr/bin` or `/usr/local/bin`. I understand why we chose to use `/opt` but maybe we should have made everything fall under `/opt/toltec` to avoid this conflict of directory purpose.

If I understand all of this correctly (which I admit I very likely don't), this exceptional usecase feels too narrow to justify losing the benefit of patchelf.

**Comment by raisjn** [comment]
the issue is not just for launchers but for any app that is compiled outside of toltec. if someone wants to compile an app outside of toltec, it will not work unless they know to use patchelf (or add a wrapper which calls the shim) or they install it into this special directory that is mentioned (but not yet implemented). this is what happened for zshelf: the person compiled it (to work with the new Qt) and were unable to launch it from any launcher in testing (or even their own custom compiled launcher if they had time to make one)

if we want to make an app for someone to test (without making it go through toltec channels), we will need to ask about their tablet every time (or publish two versions every time and tell them to pick the one that fits their tablet) or explain to them that it needs to go into a special directory

**Comment by raisjn** [comment]
for now, i will try out a systemd override on ldpreload for remux only when rm2fb is installed

**Comment by matteodelabre** [comment]
Are there other things to be addressed here apart from the things in your #338 PR @raisjn?

**Comment by matteodelabre** [comment]
Please feel free to re-open if there are additional things to fix related to this issue.
