### ISSUE TITLE
move bsdtar installation into docker image

### ISSUE THREAD

**Issue by raisjn** [matteodelabre/toltec#34]
it seems like bsdtar is being installed in the github actions / workflow, but this missing dep is also required for local builds

**Comment by matteodelabre** [comment]
bsdtar is only used for extracting the ZIP files containing the sources of each package. It is not called from within a Docker container, because the containers are only used for the parts that require the cross-compiling toolchain (i.e. the build() function). Is it not possible to install bsdtar on your system?

**Comment by raisjn** [comment]
ah, i didn't realize :( i will try that!

**Comment by matteodelabre** [comment]
I didn’t document it either (yet!) ;)

**Comment by raisjn** [comment]
perfect, this worked

**Comment by matteodelabre** [comment]
@raisjnn Does this mean we can revert https://github.com/toltec-dev/toolchain/commit/9898a35801f8c9955c5f26bc27edda488f1a54df?

**Comment by raisjn** [comment]
yes
