### ISSUE TITLE
Automate the transition to the new repository layout

### ISSUE THREAD

**Issue by Miladiir** [matteodelabre/toltec#370]
Koreader is pretty much up to date on testing, but very out of date at this point on stable. Is there a specific reason for that, or was that possibly a merge error?

**Comment by LinusCDE** [comment]
A lot of software is currently in limbo on testing. The core issue is that a lot of new architectural changes are on testing and the new merge would need to ensure that the transition goes really smoothly. We really need to push for another stable merge.

**Comment by matteodelabre** [comment]
To expand on Linus’ answer: Since #310, the repository layout in testing has been changed from a single folder containing all the packages to having subfolders containing rM1-only, rM2-only, and shared packages. If we were to merge testing to stable right now, all end-users would need to update their config in `/opt/etc/opkg.conf` accordingly before they could receive further Toltec updates. Therefore, before a new merge to stable can happen, we need to sort out a way to automate this config transition.

I’ve been working on a patch that will enable this transition, but it will probably be one or two weeks before I can finalize it. The idea is to publish a new version of the `toltec-bootstrap` package (that is present on all Toltec installs) that contains a postinstall script which takes care of updating the user’s config. Placing this update in the top-level branch folder would allow for any install with the old config to automatically pick up the update and make the transition.

**Comment by matteodelabre** [comment]
Since there wasn’t an issue for tracking the implementation of this transition process, I’m taking the opportunity to use this one to that end.

**Comment by Miladiir** [comment]
Ok, I wasn't aware of these changes. As you can probably tell, I last checked in on this project last year. I really appreciate the work you put into it. I support this change and am glad that you guys respond this way and make this internal change visible.

**Comment by matteodelabre** [comment]
On the technical level, this is fixed by #379. We’re planning to do a stable merge this week-end that will (among other things) bring KOReader up to date on stable.
