### ISSUE TITLE
RM2 All launchers freeze at "ReMarkable is starting up"

### ISSUE THREAD

**Issue by Armydoc6069** [matteodelabre/toltec#489]
I have a Remarkable 2 with Software Ver. 2.10.2.356. I have successfully installed toltec, but my device will instantly freeze any time I attempt to enable one of the available launchers. I've tried numerous fresh installs, but I always have to disable whatever launcher and re-enable xochitl and then reboot. On checking the git for rm2fb, it appears to state that 2.10.2.356 has a supported configuration. Am I missing something?

**Comment by Eeems** [comment]
We don't currently support 2.10.2.356 in stable. You'll have to switch to the testing branch, install the latest rm2fb manually,or add a configuration file to allow rm2fb to support 2.10.2.356.

**Comment by Eeems** [comment]
#486 and #445 will help keep this from happening in the future.

**Comment by LinusCDE** [comment]
I think he has a point here. I didn't get to bother with that, but I have the same issue on both devices atm. Somehow starting a launcher through `systemctl start` (or enable) doesn't start the launcher but causes the command (if typed manually) to freeze forever.

I currently have a workaround where I just create a tmux session and just run e.g. `remux` from there. Then it starts up properly and works until I reboot the device.

This is probably an issue caused by recent changes to how the systemctl units work (maybe some unintended conflict?) and seems to be unrelated to Model or rM2fb.

I should have mentioned this earlier as well, but though my device may have had some effed up setup (even though my install on both devices are installed fairly recently from scratch).

**Comment by LinusCDE** [comment]
Edit: It does seem to work on my rM 1. I think I had some initial trouble of the same kind. Will investigate more on the rM 2.

**Comment by Eeems** [comment]
remux has a known issue where a reboot is required after the first install.

**Comment by LinusCDE** [comment]
It seems that is the issue. It seems to work now. I thought I had rebooted it, but seems not so.

My guess is that the service is waiting on the required (added to `Requires=` and `After=`) input devices. I didn't even know those had services for it.

Just ran this command before rebooting (where the launcher got stuck): `systemctl status dev-input-event0.device dev-input-event1.device dev-input-event2.device`

All of those services were marked as loaded but inactive (with a single log entry noting that they were remove because they're unncessary).

After a reboot, those services are marked as loaded and `active (plugged)`. Maybe they get disabled after sleeping or something like e.g. `systemctl daemon-reload` when adding a new service file.

@raisjn do you know why you added those? They seems like more trouble now. While this seems strictly correct, was there ever doubt, those devices were absent and needed to be explicitly required?

**Comment by Eeems** [comment]
> 
> 
> It seems that is the issue. It seems to work now. I thought I had rebooted it, but seems not so.
> 
> My guess is that the service is waiting on the required (added to `Requires=` and `After=`) input devices. I didn't even know those had services for it.
> 
> Just ran this command before rebooting (where the launcher got stuck): `systemctl status dev-input-event0.device dev-input-event1.device dev-input-event2.device`
> 
> All of those services were marked as loaded but inactive (with a single log entry noting that they were remove because they're unncessary).
> 
> After a reboot, those services are marked as loaded and `active (plugged)`. Maybe they get disabled after sleeping or something like e.g. `systemctl daemon-reload` when adding a new service file.
> 
> @raisjn do you know why you added those? They seems like more trouble now. While this seems strictly correct, was there ever doubt, those devices were absent and needed to be explicitly required?

It's trying to start new instances of them for some reason, and failing because they already are started. It seems like it's an issue with how systemd implemented those device units.

They need to be in the Requires/After to ensure that the input devices have been created before remux starts up, as on boot they will sometimes not exist yet if remux starts too quick. https://github.com/toltec-dev/toltec/pull/431 https://github.com/rmkit-dev/rmkit/issues/141

**Comment by Armydoc6069** [comment]
Switching to the testing branch has Oxide working swimmingly for me. I still run into some issue with remux, however I don't really have any desire to recreate it as I've been at this process for a few days now, and it's just kind of nice to just have a working rm2. As an aside, if anyone could point me in the direction of a guide on how to actually launch the entware files I have downloaded, I would be forever grateful. I'm excited to get into angband.

**Comment by Eeems** [comment]
> if anyone could point me in the direction of a guide on how to actually launch the entware files I have downloaded, I would be forever grateful. I'm excited to get into angband.

You'll need to run it from a terminal. I'd recommend using yaft (`opkg install yaft`) which you can launch from oxide. After which you'll be able to run angband by typing in `LANG=en_US.utf8 angband` and pressing enter. Yaft does have a bug right now where you need to use the pen to input anything
![2021-11-03T191137 719](https://user-images.githubusercontent.com/1176979/140177132-359b19aa-2381-40b4-9169-c36382d7e568.png)
![2021-11-03T191431 729](https://user-images.githubusercontent.com/1176979/140177498-48c6f08b-0895-4abe-9949-0ea76bb45b4b.png)
Just to warn you, it looks like angband doesn't display well on this screen due to it needing color.

**Comment by Armydoc6069** [comment]
Eeems, you are a true hero today.

**Comment by raisjn** [comment]
afaik, all launchers need to wait for those devices to appear before starting unless they are doing something special
