### ISSUE TITLE
Toltecctl doesn't work with built-in wget

### ISSUE THREAD

**Issue by Eeems** [matteodelabre/toltec#524]
This means that using it manually to clean up a bad install will not work, and it gives users a confusing message saying to connect to wifi.

**Comment by matteodelabre** [comment]
Is this for cases where users perform a “factory reset” of their devices, thereby wiping the home partition including Toltec, but leaving the system partition as it was? Perhaps the better option would be to reflash the root partition in that case… if the Toltec install is wiped out there’s no way we can tell which packages were previously installed, and therefore we can’t hope to clean everything up automatically since any individual package can install some of its files to the root partition.

**Comment by Eeems** [comment]
It seems to be a case for when they are using sh instead of bash.

**Comment by LinusCDE** [comment]
While using the tls supporting bootstrapped wget should be the way to go, maybe tweaking the page to at least work with reMarkable would be a nice fix that suffices. Still have the nginx changes for my old site at https://rmtestrepo.cosmos-ink.net/

Nginx server entry:
```conf
server {
  # Old or minimal wget binary on rM doesn't like http2!!!
  listen 0.0.0.0:443 ssl;
  listen [::]:443 ssl;
  #listen *:80;
  # Allow older https
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:@SECLEVEL=1";
  server_name rmtestrepo.cosmos-ink.net;
  include snippets/security_headers.conf;

  root "/var/www-rmtestrepo";
  autoindex on;
}
```

I think explicitly allowing older TLS versions, makes the old wget work here. Also ensure you're not using `http2` in your listen section as this seems to cause trouble.
