### ISSUE TITLE
Interpretation of "newer than OS 2.11.0.442"

### ISSUE THREAD

**Issue by uq-at-paris-saclay** [matteodelabre/toltec#538]
https://toltec-dev.org/ says `Warning: Toltec does not yet support any OS build newer than OS 2.11.0.442. You will soft-brick your device if you install before support is released.` What is the meaning of newer than OS 2.11.0.442? Does it mean strictly newer ">", or from that version ">="?

**Comment by matteodelabre** [comment]
It is safe to install Toltec on OS 2.11.0.442, which is the latest release. This warning means that we do not yet support future versions, as we usually need a few days or weeks to make sure everything works correctly with new releases.

I’ve updated the website so that the phrasing is hopefully clearer.

**Comment by matteodelabre** [comment]
@uq-at-paris-saclay Does this answer your question?

**Comment by uq-at-paris-saclay** [comment]
Thank you, I think it is clear now!
